export const API = {
  AUTH: {
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
    REFRESH: '/auth/refresh',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
  },
  DASHBOARD: { STATS: '/dashboard/stats' },
  NAV: { BADGES: '/nav/badges' },
  SEARCH: '/search',
  CONVERSATIONS: {
    LIST: '/conversations',
    DETAIL: (id: string) => `/conversations/${id}`,
    MESSAGES: (id: string) => `/conversations/${id}/messages`,
    SEND: (id: string) => `/conversations/${id}/messages`,
    UPDATE: (id: string) => `/conversations/${id}`,
    RESOLVE: (id: string) => `/conversations/${id}/resolve`,
    ASSIGN: (id: string) => `/conversations/${id}/assign`,
    AI_TOGGLE: (id: string) => `/conversations/${id}/ai/toggle`,
    AI_SUGGEST: (id: string) => `/conversations/${id}/ai/suggest`,
    AI_SUMMARY: (id: string) => `/conversations/${id}/ai/summary`,
    NOTES: (id: string) => `/conversations/${id}/notes`,
    ATTACHMENTS: (id: string) => `/conversations/${id}/attachments`,
  },
  QUICK_REPLIES: '/quick-replies',
  CAMPAIGNS: {
    LIST: '/campaigns',
    DETAIL: (id: string) => `/campaigns/${id}`,
    STATS: '/campaigns/stats',
    ESTIMATE: '/campaigns/estimate',
    DUPLICATE: (id: string) => `/campaigns/${id}/duplicate`,
    SEND: (id: string) => `/campaigns/${id}/send`,
    PAUSE: (id: string) => `/campaigns/${id}/pause`,
    RESUME: (id: string) => `/campaigns/${id}/resume`,
    RETARGET: (id: string) => `/campaigns/${id}/retarget`,
    ARCHIVE: (id: string) => `/campaigns/${id}/archive`,
    AB_TEST: (id: string) => `/campaigns/${id}/ab-test`,
    EXPORT: (id: string) => `/campaigns/${id}/export`,
  },
  CONTACTS: {
    LIST: '/contacts',
    DETAIL: (id: string) => `/contacts/${id}`,
    STATS: '/contacts/stats',
    TAGS: '/contacts/tags',
    ADD_TAG: (id: string) => `/contacts/${id}/tags`,
    REMOVE_TAG: (id: string, tag: string) => `/contacts/${id}/tags/${tag}`,
    BLOCK: (id: string) => `/contacts/${id}/block`,
    UNBLOCK: (id: string) => `/contacts/${id}/unblock`,
    IMPORT: '/contacts/import',
    EXPORT: '/contacts/export',
  },
  SEGMENTS: {
    LIST: '/segments',
    DETAIL: (id: string) => `/segments/${id}`,
    CONTACTS: (id: string) => `/segments/${id}/contacts`,
    PREVIEW: '/segments/preview',
  },
  TEMPLATES: {
    LIST: '/templates',
    DETAIL: (id: string) => `/templates/${id}`,
    STATS: '/templates/stats',
    DUPLICATE: (id: string) => `/templates/${id}/duplicate`,
    RESUBMIT: (id: string) => `/templates/${id}/resubmit`,
  },
  BOTS: {
    LIST: '/bots',
    DETAIL: (id: string) => `/bots/${id}`,
    FLOW: (id: string) => `/bots/${id}/flow`,
    SAVE_FLOW: (id: string) => `/bots/${id}/flow`,
    PUBLISH: (id: string) => `/bots/${id}/publish`,
    UNPUBLISH: (id: string) => `/bots/${id}/unpublish`,
    TEST: (id: string) => `/bots/${id}/test`,
    STATS: (id: string) => `/bots/${id}/stats`,
  },
  AI: {
    OVERVIEW: '/ai/overview',
    MODELS: '/ai/models',
    MODEL_TOGGLE: (id: string) => `/ai/models/${id}`,
    KNOWLEDGE_BASE: '/ai/knowledge-base',
    KNOWLEDGE_DELETE: (id: string) => `/ai/knowledge-base/${id}`,
    TONE: '/ai/tone',
    GUARDRAILS: '/ai/guardrails',
    GUARDRAIL_TOGGLE: (id: string) => `/ai/guardrails/${id}`,
    CREDITS: '/ai/credits',
  },
  ANALYTICS: {
    OVERVIEW: '/analytics/overview',
    CONVERSATIONS: '/analytics/conversations',
    AGENTS: '/analytics/agents',
    AI: '/analytics/ai',
    EXPORT: '/analytics/export',
  },
  INTEGRATIONS: {
    LIST: '/integrations',
    CATEGORIES: '/integrations/categories',
    CONNECTED: '/integrations/connected',
    DETAIL: (id: string) => `/integrations/${id}`,
    CONNECT: (id: string) => `/integrations/${id}/connect`,
    DISCONNECT: (id: string) => `/integrations/${id}/disconnect`,
    CONFIG: (id: string) => `/integrations/${id}/config`,
    SYNC: (id: string) => `/integrations/${id}/sync`,
    TEST: (id: string) => `/integrations/${id}/test`,
    AI_TIPS: (id: string) => `/integrations/${id}/ai-tips`,
  },
  TEAMS: {
    LIST: '/teams',
    DETAIL: (id: string) => `/teams/${id}`,
    MEMBERS: (id: string) => `/teams/${id}/members`,
    MEMBER_DETAIL: (tId: string, mId: string) => `/teams/${tId}/members/${mId}`,
    MEMBER_STATS: (tId: string, mId: string) => `/teams/${tId}/members/${mId}/stats`,
    ROUTING: '/teams/routing',
    SCHEDULE: '/teams/schedule',
  },
  BILLING: {
    OVERVIEW: '/billing/overview',
    PLANS: '/billing/plans',
    UPGRADE: '/billing/upgrade',
    DOWNGRADE: '/billing/downgrade',
    USAGE: '/billing/usage',
    TOP_UP: '/billing/top-up',
    TRANSACTIONS: '/billing/transactions',
    INVOICES: '/billing/invoices',
    INVOICE_DOWNLOAD: (id: string) => `/billing/invoices/${id}/download`,
    AI_INSIGHTS: '/billing/ai-insights',
  },
  NOTIFICATIONS: {
    LIST: '/notifications',
    MARK_READ: (id: string) => `/notifications/${id}/read`,
    MARK_ALL_READ: '/notifications/read-all',
    UNREAD_COUNT: '/notifications/unread-count',
  },
  SETTINGS: {
    GENERAL: { GET: '/settings/general', UPDATE: '/settings/general', UPLOAD_LOGO: '/settings/general/logo' },
    SECURITY: {
      GET: '/settings/security',
      UPDATE: '/settings/security',
      CHANGE_PASSWORD: '/settings/security/password',
      SESSIONS: '/settings/security/sessions',
      TERMINATE_SESSION: (id: string) => `/settings/security/sessions/${id}`,
      TERMINATE_ALL: '/settings/security/sessions/terminate-all',
      ENABLE_2FA: '/settings/security/2fa/enable',
      DISABLE_2FA: '/settings/security/2fa/disable',
      IP_WHITELIST: '/settings/security/ip-whitelist',
      AUDIT_LOG: '/settings/security/audit-log',
    },
    NOTIFICATIONS: { GET: '/settings/notifications', UPDATE: '/settings/notifications' },
    SLA: { GET: '/settings/sla', UPDATE: '/settings/sla' },
    CONVERSATIONS: { GET: '/settings/conversations', UPDATE: '/settings/conversations' },
    SMS: { GET: '/settings/sms', UPDATE: '/settings/sms' },
    AUTO_MESSAGES: { GET: '/settings/auto-messages', UPDATE: '/settings/auto-messages' },
    BUSINESS_HOURS: { GET: '/settings/business-hours', UPDATE: '/settings/business-hours' },
    API_KEYS: {
      LIST: '/settings/api-keys',
      CREATE: '/settings/api-keys',
      DELETE: (id: string) => `/settings/api-keys/${id}`,
      REGENERATE: (id: string) => `/settings/api-keys/${id}/regenerate`,
    },
    WEBHOOKS: {
      LIST: '/settings/webhooks',
      CREATE: '/settings/webhooks',
      UPDATE: (id: string) => `/settings/webhooks/${id}`,
      DELETE: (id: string) => `/settings/webhooks/${id}`,
      TEST: (id: string) => `/settings/webhooks/${id}/test`,
      LOGS: (id: string) => `/settings/webhooks/${id}/logs`,
    },
    WHATSAPP: {
      GET: '/settings/whatsapp',
      UPDATE: '/settings/whatsapp',
      NUMBERS: '/settings/whatsapp/numbers',
      ADD_NUMBER: '/settings/whatsapp/numbers',
      REMOVE_NUMBER: (id: string) => `/settings/whatsapp/numbers/${id}`,
    },
  },
};
