"use client";

import {
  Activity,
  Award,
  BarChart3,
  Bell,
  Bookmark,
  BookOpen,
  Bot,
  Brain,
  Check,
  CheckCheck,
  Copy,
  CreditCard,
  FileText,
  Globe,
  Inbox,
  Key,
  LayoutGrid,
  Link as LinkIcon,
  ListChecks,
  Loader,
  Lock,
  LogOut,
  type LucideIcon,
  Megaphone,
  Menu,
  MessageCircle,
  Moon,
  Package,
  Paperclip,
  Pencil,
  PieChart,
  Plug,
  RefreshCw,
  Receipt,
  Rocket,
  Search,
  Send,
  Settings,
  Sheet,
  ShoppingCart,
  Shield,
  Smartphone,
  Smile,
  Sparkles,
  Star,
  Store,
  Sun,
  Tag,
  Target,
  Timer,
  Trash2,
  Truck,
  UserPlus,
  Users,
  Wallet,
  X,
  Zap,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  dashboard: LayoutGrid,
  inbox: Inbox,
  megaphone: Megaphone,
  users: Users,
  file: FileText,
  bot: Bot,
  brain: Brain,
  chart: BarChart3,
  link: LinkIcon,
  team: UserPlus,
  card: CreditCard,
  gear: Settings,
  search: Search,
  menu: Menu,
  x: X,
  bell: Bell,
  sun: Sun,
  moon: Moon,
  globe: Globe,
  send: Send,
  clip: Paperclip,
  smile: Smile,
  check: Check,
  dcheck: CheckCheck,
  wallet: Wallet,
  msg: MessageCircle,
  rocket: Rocket,
  zap: Zap,
  tag: Tag,
  bookmark: Bookmark,
  book: BookOpen,
  shield: Shield,
  lock: Lock,
  phone: Smartphone,
  pkg: Package,
  truck: Truck,
  cart: ShoppingCart,
  userPlus: UserPlus,
  star: Star,
  pencil: Pencil,
  target: Target,
  award: Award,
  list: ListChecks,
  key: Key,
  copy: Copy,
  plug: Plug,
  logout: LogOut,
  store: Store,
  pie: PieChart,
  receipt: Receipt,
  sheet: Sheet,
  refresh: RefreshCw,
  activity: Activity,
  timer: Timer,
  sparkles: Sparkles,
  loader: Loader,
  trash: Trash2,
};

interface IconProps {
  name: string;
  size?: number;
}

export function Icon({ name, size = 16 }: IconProps) {
  const LucideComp = ICON_MAP[name];
  if (!LucideComp) return null;
  return <LucideComp size={size} strokeWidth={1.8} />;
}
