"use client";

import {
  Activity,
  AlertTriangle,
  Award,
  Ban,
  BarChart3,
  Bell,
  Bookmark,
  BookOpen,
  Bot,
  Brain,
  Cable,
  Cake,
  Calendar,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleDot,
  Cloud,
  Code,
  Copy,
  CreditCard,
  DollarSign,
  Download,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Film,
  Flag,
  Flame,
  Frown,
  Gem,
  Globe,
  Hand,
  Handshake,
  Heart,
  Image as ImageIcon,
  Inbox,
  Info,
  Key,
  LayoutGrid,
  Link as LinkIcon,
  ListChecks,
  Loader,
  Lock,
  LogOut,
  type LucideIcon,
  Mail,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  Moon,
  Moon as MoonZ,
  Package,
  Paperclip,
  Pencil,
  PieChart,
  Plug,
  Plus,
  RefreshCw,
  Receipt,
  Reply,
  Rocket,
  Search,
  Send,
  Settings,
  Sheet,
  Shuffle,
  ShoppingBag,
  ShoppingCart,
  Shield,
  Siren,
  Smartphone,
  Smile,
  Languages,
  Meh,
  Sparkles,
  Star,
  Store,
  Sun,
  Tag,
  Target,
  Timer,
  TrendingDown,
  TrendingUp,
  Trash2,
  Truck,
  Type,
  Upload,
  User,
  UserPlus,
  Users,
  Video,
  Volume2,
  Wallet,
  Wand2,
  Webhook,
  X,
  Zap,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  dashboard: LayoutGrid,
  inbox: Inbox,
  megaphone: Megaphone,
  users: Users,
  file: FileText,
  bot: Bot,
  brain: Brain,
  chart: BarChart3,
  link: LinkIcon,
  team: UserPlus,
  card: CreditCard,
  gear: Settings,
  search: Search,
  menu: Menu,
  x: X,
  bell: Bell,
  sun: Sun,
  moon: Moon,
  globe: Globe,
  send: Send,
  clip: Paperclip,
  smile: Smile,
  check: Check,
  dcheck: CheckCheck,
  wallet: Wallet,
  msg: MessageCircle,
  rocket: Rocket,
  zap: Zap,
  tag: Tag,
  bookmark: Bookmark,
  book: BookOpen,
  shield: Shield,
  lock: Lock,
  phone: Smartphone,
  pkg: Package,
  truck: Truck,
  cart: ShoppingCart,
  userPlus: UserPlus,
  star: Star,
  pencil: Pencil,
  target: Target,
  award: Award,
  list: ListChecks,
  key: Key,
  copy: Copy,
  plug: Plug,
  logout: LogOut,
  store: Store,
  pie: PieChart,
  receipt: Receipt,
  sheet: Sheet,
  refresh: RefreshCw,
  activity: Activity,
  timer: Timer,
  sparkles: Sparkles,
  loader: Loader,
  trash: Trash2,
  ban: Ban,
  channels: Cable,
  code: Code,
  video: Video,
  film: Film,
  image: ImageIcon,
  text: Type,
  msgSquare: MessageSquare,
  alert: AlertTriangle,
  cake: Cake,
  calendar: Calendar,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  cloud: Cloud,
  dollar: DollarSign,
  download: Download,
  eye: Eye,
  eyeOff: EyeOff,
  filter: Filter,
  fire: Flame,
  gem: Gem,
  hand: Hand,
  handshake: Handshake,
  heart: Heart,
  info: Info,
  mail: Mail,
  moonZ: MoonZ,
  plus: Plus,
  reply: Reply,
  shoppingBag: ShoppingBag,
  siren: Siren,
  trending: TrendingUp,
  upload: Upload,
  user: User,
  volume: Volume2,
  wand: Wand2,
  webhook: Webhook,
  circle: CircleDot,
  shuffle: Shuffle,
  flag: Flag,
  frown: Frown,
  meh: Meh,
  translate: Languages,
  circleDot: Circle,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
};

interface IconProps {
  name: string;
  size?: number;
}

export function Icon({ name, size = 16 }: IconProps) {
  const LucideComp = ICON_MAP[name];
  if (!LucideComp) return null;
  return <LucideComp size={size} strokeWidth={1.8} />;
}
